# Generated by Django 4.0.4 on 2022-05-08 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('acadYear', models.TextField()),
                ('preclusion', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('title', models.TextField()),
                ('department', models.TextField()),
                ('faculty', models.TextField()),
                ('workload', models.TextField(blank=True, null=True)),
                ('prerequisite', models.TextField(blank=True, null=True)),
                ('moduleCredit', models.TextField()),
                ('moduleCode', models.TextField()),
                ('semesterData', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('prereqTree', models.JSONField(blank=True, null=True)),
                ('fulfillRequirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCondensed',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('moduleCode', models.TextField()),
                ('title', models.TextField()),
                ('semesters', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
